[package]
name = "indexer"
version = "0.1.0"
authors = ["Xuejie Xiao <xxuejie@gmail.com>"]
license = "MIT"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ckb-indexer = { git = "https://github.com/nervosnetwork/ckb-indexer", rev = "d247556" }
ckb-jsonrpc-types = "0.40.0"
ckb-types = "0.40.0"
env_logger = "0.7.1"
futures = "0.3"
jsonrpc-core = "17.0"
jsonrpc-core-client = { version = "17.0", features = ["http", "tls"] }
jsonrpc-derive = "17.0"
log = "0.4.8"
num_cpus = "1.13.0"
serde_json = "1.0.59"
lazysort = "0.2.1"
tokio = { version = "0.2", features = ["full"] }
tokio-compat-02 = "0.2.0"

[dependencies.neon]
version = "0.8.3"
default-features = false
features = ["napi-4", "event-queue-api"]
